version: '3.8'
services:
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   command: python app/main.py
  #   depends_on:
  #     - mongodb
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - caddy-data:/data
  #     - caddy-config:/config
  #   depends_on:
  #     - backend
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=mydb

volumes:
  caddy-data:
  caddy-config: